import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import SharedReading from "@/pages/SharedReading";

// Mock i18n
vi.mock("react-i18next", () => ({
  useTranslation: () => ({
    t: (key: string, params?: Record<string, unknown>) => {
      const translations: Record<string, string> = {
        "common.loading": "Loading...",
        "oracle.shared_reading_title": "NPS Oracle Reading",
        "oracle.shared_reading_footer": "Generated by NPS Oracle",
        "oracle.share_views": `${params?.count ?? 0} views`,
        "oracle.share_expired": "This link has expired",
        "oracle.share_not_found": "Reading not found or link expired",
        "oracle.question_label": "Question",
        "oracle.tab_summary": "Summary",
        "oracle.ai_interpretation": "AI Interpretation",
        "oracle.disclaimer": "For entertainment only.",
      };
      return translations[key] || key;
    },
    i18n: { language: "en" },
  }),
}));

const mockShareGet = vi.fn();
vi.mock("@/services/api", () => ({
  share: {
    get: (...args: unknown[]) => mockShareGet(...args),
  },
}));

function renderSharedReading(token: string = "test-token") {
  return render(
    <MemoryRouter initialEntries={[`/share/${token}`]}>
      <Routes>
        <Route path="/share/:token" element={<SharedReading />} />
      </Routes>
    </MemoryRouter>,
  );
}

describe("SharedReading", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("renders loading state initially", () => {
    mockShareGet.mockReturnValue(new Promise(() => {}));
    renderSharedReading();
    expect(screen.getByText("Loading...")).toBeInTheDocument();
  });

  it("renders reading data on success", async () => {
    mockShareGet.mockResolvedValue({
      reading: {
        id: 1,
        sign_type: "time",
        sign_value: "12:00:00",
        question: "Test question",
        ai_interpretation: "The stars say...",
        created_at: "2026-01-01T00:00:00Z",
        is_favorite: false,
        reading_result: { summary: "A great reading" },
      },
      shared_at: "2026-01-01T00:00:00Z",
      view_count: 5,
    });

    renderSharedReading();

    await waitFor(() => {
      expect(screen.getByText("NPS Oracle")).toBeInTheDocument();
    });
    expect(screen.getByText("Test question")).toBeInTheDocument();
    expect(screen.getByText("The stars say...")).toBeInTheDocument();
    expect(screen.getByText("5 views")).toBeInTheDocument();
  });

  it("renders error for invalid token", async () => {
    mockShareGet.mockRejectedValue({ status: 404 });

    renderSharedReading("bad-token");

    await waitFor(() => {
      expect(
        screen.getByText("Reading not found or link expired"),
      ).toBeInTheDocument();
    });
  });

  it("renders outside Layout (no sidebar)", async () => {
    mockShareGet.mockResolvedValue({
      reading: {
        id: 1,
        sign_type: "time",
        sign_value: "12:00:00",
        question: null,
        ai_interpretation: null,
        created_at: "2026-01-01T00:00:00Z",
        is_favorite: false,
        reading_result: null,
      },
      shared_at: "2026-01-01T00:00:00Z",
      view_count: 1,
    });

    renderSharedReading();

    await waitFor(() => {
      expect(screen.getByText("NPS Oracle")).toBeInTheDocument();
    });
    // No sidebar elements should be present
    expect(screen.queryByRole("navigation")).not.toBeInTheDocument();
  });

  it("sets document title with reading info", async () => {
    mockShareGet.mockResolvedValue({
      reading: {
        id: 1,
        sign_type: "time",
        sign_value: "12:00:00",
        question: null,
        ai_interpretation: "Test interp",
        created_at: "2026-01-01T00:00:00Z",
        is_favorite: false,
        reading_result: null,
      },
      shared_at: "2026-01-01T00:00:00Z",
      view_count: 0,
    });

    renderSharedReading();

    await waitFor(() => {
      expect(document.title).toContain("NPS Oracle Reading");
    });
  });
});
