import { describe, it, expect, vi } from "vitest";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { ShareButton } from "../ShareButton";
import type { ConsultationResult } from "@/types";

vi.mock("react-i18next", () => ({
  useTranslation: () => ({
    t: (key: string) => {
      const map: Record<string, string> = {
        "oracle.share": "Share",
        "oracle.copied": "Copied!",
        "oracle.shared_reading_title": "NPS Oracle Reading",
        "oracle.date_label": "Date",
        "oracle.reading_type": "Reading Type",
        "oracle.type_time_title": "Time Reading",
        "oracle.type_name_title": "Name Reading",
        "oracle.type_question_title": "Question Reading",
        "oracle.element": "Element",
        "oracle.energy": "Energy",
        "oracle.life_path": "Life Path",
        "oracle.export_generated_by": "Generated by NPS",
        "oracle.question_label": "Question",
        "oracle.question_number_label": "Question Number",
        "oracle.field_name": "Name",
        "oracle.expression": "Expression",
        "oracle.soul_urge": "Soul Urge",
        "oracle.personality": "Personality",
        "oracle.details_moon_phase": "Moon Phase",
      };
      return map[key] ?? key;
    },
    i18n: { language: "en", changeLanguage: vi.fn() },
  }),
}));

const result: ConsultationResult = {
  type: "reading",
  data: {
    fc60: {
      cycle: 1,
      element: "Wood",
      polarity: "Yang",
      stem: "Jia",
      branch: "Zi",
      year_number: 1,
      month_number: 2,
      day_number: 3,
      energy_level: 7,
      element_balance: { Wood: 3 },
    },
    numerology: {
      life_path: 5,
      day_vibration: 3,
      personal_year: 1,
      personal_month: 4,
      personal_day: 7,
      interpretation: "",
    },
    zodiac: null,
    chinese: null,
    moon: null,
    angel: null,
    chaldean: null,
    ganzhi: null,
    fc60_extended: null,
    synchronicities: [],
    ai_interpretation: null,
    summary: "Test summary",
    generated_at: "2024-01-01T12:00:00Z",
  },
};

describe("ShareButton", () => {
  it("calls clipboard.writeText with generated summary", async () => {
    const writeText = vi.fn().mockResolvedValue(undefined);
    Object.assign(navigator, {
      clipboard: { writeText },
    });

    render(<ShareButton result={result} />);
    await userEvent.click(screen.getByText("Share"));

    expect(writeText).toHaveBeenCalledTimes(1);
    const text = writeText.mock.calls[0][0];
    expect(text).toContain("NPS Oracle Reading");
    expect(text).toContain("Test summary");
    expect(text).toContain("Life Path: 5");
  });

  it("shows 'Copied!' text after click", async () => {
    Object.assign(navigator, {
      clipboard: { writeText: vi.fn().mockResolvedValue(undefined) },
    });

    render(<ShareButton result={result} />);
    await userEvent.click(screen.getByText("Share"));

    await waitFor(() => {
      expect(screen.getByText("Copied!")).toBeInTheDocument();
    });
  });
});
